apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: REMOVED.dkr.ecr.us-east-1.amazonaws.com/wordflow/frontend:0.0.0.4
        ports:
        - containerPort: 80
