# postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: wordflow_db
        - name: POSTGRES_USER
          value: benjaminbradford
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
