name: Build and Push to ECR

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    
    - name: Setup kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name wordflow

    - name: Build and push backend image
      run: |
        IMAGE_URI=$ECR_REGISTRY/wordflow/backend:$IMAGE_TAG
        docker build --no-cache -t $IMAGE_URI ./wordflow-api
        docker push $IMAGE_URI
        env IMAGE_URI=$IMAGE_URI envsubst < k8s/backend-deployment.yaml | kubectl apply -f -

    - name: Build and push frontend image
      run: |
        IMAGE_URI=$ECR_REGISTRY/wordflow/frontend:$IMAGE_TAG
        docker build --no-cache -t $IMAGE_URI ./wordflow
        docker push $IMAGE_URI
        env IMAGE_URI=$IMAGE_URI envsubst < k8s/frontend-deployment.yaml | kubectl apply -f -
